---
- name: provision deps
  hosts: '*'
  tasks:
    - name: install deps
      become: true
      apt:
        install_recommends: no
        autoclean: yes
        autoremove: yes
        update_cache: true
        pkg:
          - git
          - curl
          - wireguard
          - wireguard-tools
          - wireguard-dkms
          - gnupg
          - unzip
        # pkg:
        #   - libodbc1
        #   - libsctp1
        #   - libwxgtk3.0-0v5
        #   - libwxgtk3.0-dev
        #   - unixodbc-dev
        #   - libsctp-dev
        #   - autoconf
        #   - automake
        #   - bzip2
        #   - dpkg-dev
        #   - file
        #   - g++
        #   - gcc
        #   - imagemagick
        #   - libbz2-dev
        #   - libc6-dev
        #   - libcurl4-openssl-dev
        #   - libdb-dev
        #   - libevent-dev
        #   - libffi-dev
        #   - libgdbm-dev
        #   - libglib2.0-dev
        #   - libgmp-dev
        #   - libjpeg-dev
        #   - libkrb5-dev
        #   - liblzma-dev
        #   - libmagickcore-dev
        #   - libmagickwand-dev
        #   - libmaxminddb-dev
        #   - libncurses5-dev
        #   - libncursesw5-dev
        #   - libpng-dev
        #   - libpq-dev
        #   - libreadline-dev
        #   - libsqlite3-dev
        #   - libssl-dev
        #   - libtool
        #   - libwebp-dev
        #   - libxml2-dev
        #   - libxslt-dev
        #   - libyaml-dev
        #   - make
        #   - patch
        #   - xz-utils
        #   - zlib1g-dev
        #   - linux-image-generic-hwe-18.04-edge
        #   - linux-headers-generic-hwe-18.04-edge
        #   - git
        #   - curl
        #   - ca-certificates
        #   - resolvconf
        #   - gnupg
        #   - wireguard
        #   - wireguard-tools
        #   - wireguard-dkms

- name: Install Postgres
  hosts: '*'
  tasks:
    - name: add postgres repo
      become: true
      shell: |
        curl https://www.postgresql.org/media/keys/ACCC4CF8.asc | apt-key add -
        sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
    - name: install postgres
      become: true
      apt:
        update_cache: true
        install_recommends: no
        autoclean: yes
        autoremove: yes
        name: postgresql-13

- name: Configure System
  hosts: '*'
  tasks:
    - name: copy files
      become: true
      shell: |
        cp /vagrant/ansible/sample_conf/wg-server.conf /etc/wireguard/wg0.conf
    - name: ensure ipv4 forward
      become: true
      lineinfile:
        path: /etc/sysctl.conf
        line: 'net.ipv4.ip_forward = 1'
    - name: ensure ipv6 forward
      become: true
      lineinfile:
        path: /etc/sysctl.conf
        line: 'net.ipv6.conf.all.forwarding = 1'
    - name: apply sysctl
      become: true
      shell: sysctl -p

- name: Provision Runtimes
  hosts: '*'
  tasks:
    - name: install erlang
      become: true
      apt:
        install_recommends: no
        autoclean: yes
        autoremove: yes
        update_cache: true
        deb: https://packages.erlang-solutions.com/erlang/debian/pool/esl-erlang_23.1-1~ubuntu~focal_amd64.deb
    - name: install elixir
      become: false
      shell:
        executable: /bin/bash
        cmd: |
          [ ! -d ~/.asdf ] && git clone https://github.com/asdf-vm/asdf.git ~/.asdf --branch v0.8.0
          ~/.asdf/bin/asdf plugin-add elixir
          ~/.asdf/bin/asdf install elixir 1.11.1-otp-23
          ~/.asdf/bin/asdf global elixir 1.11.1-otp-23
          ~/.asdf/bin/asdf reshim elixir 1.11.1-otp-23
    - name: asdf to bashrc
      become: false
      lineinfile:
        path: ~/.bashrc
        line: '. ~/.asdf/asdf.sh'
    - name: asdf completions to bashrc
      become: false
      lineinfile:
        path: ~/.bashrc
        line: '. ~/.asdf/completions/asdf.bash'
