---
- name: provision deps
  hosts: all
  become: yes
  tasks:
    - name: install deps
      apt:
        install_recommends: no
        autoclean: yes
        autoremove: yes
        update_cache: true
        pkg:
          - sudo
          - git
          - curl
          - gnupg
          - unzip
          - dpkg-dev
          - wireguard
          - postgresql
          - iptables
          - net-tools
          - automake
          - autoconf
          - libssl-dev
          - libncurses5-dev
          - zlib1g-dev
          - locales
          - build-essential
          - ca-certificates

    - name: setup nodejs repository
      shell: curl -sL https://deb.nodesource.com/setup_10.x | bash -
    - name: install nodejs
      apt:
        install_recommends: no
        autoclean: yes
        autoremove: yes
        pkg:
          - nodejs
    - name: install erlang
      apt:
        deb: https://packages.erlang-solutions.com/erlang/debian/pool/esl-erlang_23.1-1~ubuntu~focal_amd64.deb
    - name: install elixir
      apt:
        deb: https://packages.erlang-solutions.com/erlang/debian/pool/elixir_1.11.2-1~ubuntu~focal_all.deb
- name: Configure System
  hosts: all
  become: yes
  tasks:
    - name: ensure ipv4 forward
      lineinfile:
        path: /etc/sysctl.conf
        line: 'net.ipv4.ip_forward = 1'
    - name: ensure ipv6 forward
      lineinfile:
        path: /etc/sysctl.conf
        line: 'net.ipv6.conf.all.forwarding = 1'
    - name: apply sysctl
      shell: sysctl -p
- name: Build FireGuard
  hosts: all
  tasks:
    - name: Copy Project
      copy:
        src: /vagrant
        dest: /home/vagrant/fireguard
    - name: Compile Release
      become: no
      environment:
        MIX_ENV: prod
      shell: |
        cd /home/vagrant/fireguard
        scripts/build_release.sh
    - name: Build Debian Package
      become: no
      shell: |
        cd /home/vagrant/fireguard
        scripts/build_deb.sh
    - name: Install FireGuard deb
      become: yes
      shell: |
        cd /home/vagrant/fireguard
        dpkg -i fireguard_amd64.deb
