---
- name: provision deps
  hosts: all
  become: yes
  tasks:
    - name: install deps
      apt:
        install_recommends: no
        autoclean: yes
        autoremove: yes
        update_cache: true
        pkg:
          - rsync
          - sudo
          - git
          - curl
          - gnupg
          - unzip
          - dpkg-dev
          - wireguard
          - postgresql
          - iptables
          - net-tools
          - automake
          - autoconf
          - libssl-dev
          - libncurses5-dev
          - zlib1g-dev
          - locales
          - build-essential
          - ca-certificates

    - name: setup nodejs repository
      shell: curl -sL https://deb.nodesource.com/setup_14.x | bash -
    - name: install nodejs
      apt:
        install_recommends: no
        autoclean: yes
        autoremove: yes
        pkg:
          - nodejs
    - name: install erlang
      apt:
        deb: https://packages.erlang-solutions.com/erlang/debian/pool/esl-erlang_23.2-1~ubuntu~focal_amd64.deb
    - name: install elixir
      apt:
        deb: https://packages.erlang-solutions.com/erlang/debian/pool/elixir_1.11.2-1~ubuntu~focal_all.deb
- name: Configure System
  hosts: all
  become: yes
  tasks:
    - name: ensure ipv4 forward
      lineinfile:
        path: /etc/sysctl.conf
        line: 'net.ipv4.ip_forward = 1'
    - name: ensure ipv6 forward
      lineinfile:
        path: /etc/sysctl.conf
        line: 'net.ipv6.conf.all.forwarding = 1'
    - name: apply sysctl
      shell: sysctl -p
- name: Build FireZone
  hosts: all
  tasks:
    - name: Copy Project
      shell: |
        rsync --delete -avz --exclude '_build' --exclude 'deps' /vagrant/* /home/vagrant/firezone/
    - name: Compile Release
      become: no
      environment:
        MIX_ENV: prod
      shell: |
        cd /home/vagrant/firezone
        scripts/build_release.sh
    - name: Build Debian Package
      become: no
      shell: |
        cd /home/vagrant/firezone
        scripts/build_deb.sh
    - name: Install FireZone deb
      become: yes
      shell: |
        cd /home/vagrant/firezone
        dpkg -i firezone_amd64.deb
    - name: Enable systemd units
      become: yes
      shell: |
        systemctl enable firezone
    - name: Start systemd units
      become: yes
      shell: |
        systemctl start firezone
    - name: Capture user credentials
      become: yes
      shell: |
        journalctl -u firezone
      register: create_user
    - name: Display user credentials
      debug: msg="{{ create_user.stdout_lines }}"
