[package]
name = "fgvpn_server"
version = "0.1.0"
authors = []
edition = "2018"

[lib]
name = "fgvpn_server"
path = "src/lib.rs"
crate-type = ["dylib"]

[dependencies]
rustler = "0.22.0-rc.0"
boringtun = "0.3.0"
