name: Build base images
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  build-and-push:
    strategy:
      matrix:
        os:
          - amazonlinux_2
          - centos_7
          - centos_8
          - fedora_33
          - fedora_34
          - fedora_35
          - debian_10
          - ubuntu_18.04
          - ubuntu_20.04
    runs-on: ubuntu-20.04
    steps:
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v2
      - run: scripts/build_and_push_base_images.sh
