name: Build base images
on:
  workflow_dispatch:
  schedule:
    - cron: '0 10 * * *' # 10am UTC

jobs:
  build-and-push:
    env:
      MATRIX_IMAGE: ${{ matrix.image }}
      MATRIX_PLATFORM: ${{ matrix.platform }}
    strategy:
      matrix:
        image:
          - amazonlinux:2
          - centos:7
          - centos:8
          - fedora:33
          - fedora:34
          - fedora:35
          - debian:10
          - ubuntu:18.04
          - ubuntu:20.04
        platform:
          - linux/amd64
    runs-on: ubuntu-20.04
    steps:
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v2
      - run: |
          # Required due to a buildx bug.
          # See https://github.com/docker/buildx/issues/495#issuecomment-761562905
          docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
          docker buildx create --name multiarch --driver docker-container --use
          docker buildx inspect --bootstrap
          .ci/build_base.sh
