name: Build base images
on:
  - workflow_dispatch
  - schedule:
    - cron: '0 0 * * *'

jobs:
  build-and-push:
    runs-on: ubuntu-20.04
    steps:
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: action/checkout@v2
      - run: scripts/build_and_push_base_images.sh

