name: CI
on:
  - push
defaults:
  run:
    shell: bash

jobs:
  unit-integration-test:
    runs-on: ${{ matrix.os }}
    env:
      MIX_ENV: test
      POSTGRES_HOST: localhost
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      MATRIX_OS: ubuntu-18.04
    strategy:
      matrix:
        os:
          - ubuntu-20.04
          - ubuntu-18.04
        postgres:
          - postgres:9.6
          - postgres:10
          - postgres:11
          - postgres:12
          - postgres:13
    services:
      postgres:
        image: ${{ matrix.postgres }}
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Install package dependencies
        run: sudo apt-get install net-tools wireguard unzip gdebi
      - uses: actions/checkout@v2
      - name: Install Runtimes
        run: |
          sudo -E bash -c '.ci/install_runtimes.sh'
      - name: Install Dependencies
        run: .ci/install_dependencies.sh
      - uses: actions/cache@v2
        with:
          path: |
            deps
            _build
          key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-mix-
      - name: Setup Database
        run: |
          mix ecto.create
          mix ecto.migrate
      - name: Run Tests and Upload Coverage Report
        run: mix coveralls.github --umbrella
      - uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: test screenshots
          path: apps/fz_http/screenshots

  build:
    needs: unit-integration-test
    runs-on: ubuntu-20.04
    name: Build
    env:
      MATRIX_IMAGE: ${{ matrix.image }}
      MATRIX_PLATFORM: ${{ matrix.platform }}
      MIX_ENV: prod
    strategy:
      matrix:
        platform:
          - linux/amd64
        image:
          - centos:7
          - centos:8
          - debian:10
          - fedora:33
          - fedora:34
          - ubuntu:18.04
          - ubuntu:20.04
    steps:
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v2
      - run: |
          .ci/build_packages.sh

      - uses: actions/upload-artifact@v2
        with:
          name: firezone
          path: |
            _build/firezone*.rpm
            _build/firezone*.deb

  functional-test:
    needs: build
    runs-on: macos-latest # macos supports Virtualbox / Vagrant
    env:
      MATRIX_OS: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - centos_7
          - centos_8
          - debian_10
          - fedora_33
          - fedora_34
          - ubuntu_18.04
          - ubuntu_20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: firezone
          path: ./
      - run: |
          vagrant cloud auth login --token ${{ secrets.VAGRANT_TOKEN }}
      - uses: actions/cache@v2
        with:
          path: |
            ~/.vagrant.d/boxes
          key: ${{ runner.os }}-${{ hashFiles('.ci/vagrant-runner-cache') }}
      - run: vagrant up ${{ matrix.os }}
      - run: .ci/functional_test.sh

  publish:
    needs: functional-test
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        os:
          - debian_10
          - ubuntu_18.04
          - ubuntu_20.04
          - centos_7
          - centos_8
          - fedora_33
          - fedora_34
    if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: true
      - uses: actions/download-artifact@v2
        with:
          name: firezone_${{ matrix.os }}_amd64
          path: ./
      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./firezone_${{ matrix.os }}_amd64.deb
          asset_name: ${{ matrix.os }}_amd64
          asset_content_type: application/vnd.debian.binary-package
